import numpy as np
arr1= np.array ([1,23,3,4,5,])
print("1D Array:")
print(arr1)
print("Shape:",arr1.shape)
print("Dimensions:",arr1.ndim)
print("Size:",arr1.size)
print("Data Type:",arr1.dtype)
print("Item Size:",arr1.itemsize)
print("Nbytes:",arr1.nbytes)
print("Array Type:",type(arr1))
print("Array Contains:")
print(arr1)
print()